services:
  dinasore:
    container_name: dinasore
    hostname: dinasore

    build:
      dockerfile: dinasore/Dockerfile

    restart: unless-stopped
    pull_policy: always

    network_mode: host

    healthcheck:
      test: ["CMD-SHELL", "python3 /sinf/dinasore/tests/__init__.py"]
      interval: 1m
      timeout: 30s
      retries: 10

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:17-alpine

    restart: unless-stopped
    pull_policy: always

    shm_size: 256mb

    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_DB

    ports:
      - 5432:5432

    volumes:
      - ./data/postgres:/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10

  pgadmin:
    container_name: pgadmin
    hostname: pgadmin
    image: dpage/pgadmin4

    restart: unless-stopped

    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD

    ports:
      - 8080:80

    depends_on:
      - postgres

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:main

    restart: unless-stopped

    user: "${UID}:${GID}"

    environment:
      - GF_SERVER_HTTP_PORT=3000
      - GF_SECURITY_ADMIN_PASSWORD
      - GF_SECURITY_ADMIN_USER
      - UID
      - GID

    ports:
      - 8081:3000

    volumes:
      - ./data/grafana:/var/lib/grafana

