{
 "title": "Anomalies Records",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Station",
    "query": "SELECT DISTINCT station_id FROM DINASORE.Sensor ORDER BY station_id;\n"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"\n  width: 100%;\n  height: 100px;\n  background: linear-gradient(135deg, #27ae60, #2ecc71);\n  color: white;\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  padding: 0 30px;\n  font-size: 20px;\n  font-weight: bold;\n  border-radius: 8px;\n  box-sizing: border-box;\n\">\n  <div>📉 Anomalies Records Dashboard</div>\n  <div>\n    <a href=\"/d/930122ff-4ef3-4351-ae53-f38ad5c228b0/home\" style=\"\n      color: white;\n      text-decoration: underline;\n      font-size: 14px;\n      font-weight: normal;\n      text-decoration: none;\n    \">\n      ⬅ Back to Home\n    </a>\n  </div>\n</div>"
   }
  },
  {
   "title": "Defects Station ${Station}",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(*) AS defects\r\nFROM DINASORE.Measurement m\r\nJOIN DINASORE.Sensor s ON m.sensor_id = s.sensor_id\r\nWHERE m.anomaly_flag = TRUE\r\n  AND s.station_id = $Station\r\n  AND m.timestamp > now() - INTERVAL '5 minutes';\r\n"
    }
   ]
  },
  {
   "title": "Defects Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  s.station_id  AS \"Station\",\r\n  COUNT(*)       AS \"Defects\"\r\nFROM DINASORE.Measurement m\r\nJOIN DINASORE.Sensor      s ON m.sensor_id = s.sensor_id\r\nWHERE m.anomaly_flag = TRUE\r\nGROUP BY s.station_id\r\nORDER BY s.station_id;\r\n"
    }
   ]
  },
  {
   "title": "Stop/Start Actuators ",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ts        AS \"Time\",\r\n  station_id AS \"Station\",\r\n  action    AS \"Action\"\r\nFROM DINASORE.ActionLog\r\nORDER BY ts DESC\r\nLIMIT 20;\r\n"
    }
   ]
  },
  {
   "title": "Estação $Station – Anomalias",
   "type": "stat",
   "gridPos": { "h": 0, "w": 24, "x": 0, "y": 23 },
   "repeat": "Station",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(*) AS defects\r\nFROM DINASORE.Measurement m\r\nJOIN DINASORE.Sensor s ON m.sensor_id = s.sensor_id\r\nWHERE m.anomaly_flag = TRUE\r\n  AND s.station_id = $Station;\r\n"
    }
   ]
  }
 ]
}