{
 "title": "Measurements Dashboard",
 "time": { "from": "2025-05-03T12:53:00.000Z", "to": "2025-05-03T12:59:59.000Z" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"\n  width: 100%;\n  height: 100px;\n  background: linear-gradient(135deg, #27ae60, #2ecc71);\n  color: white;\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  padding: 0 30px;\n  font-size: 20px;\n  font-weight: bold;\n  border-radius: 8px;\n  box-sizing: border-box;\n\">\n  <div>📊 Measurements Monitoring Dashboard</div>\n  <div>\n    <a href=\"/d/930122ff-4ef3-4351-ae53-f38ad5c228b0/home\" style=\"\n      color: white;\n      text-decoration: underline;\n      font-size: 14px;\n      font-weight: normal;\n      text-decoration: none;\n    \">\n      ⬅ Back to Home\n    </a>\n  </div>\n</div>"
   }
  },
  {
   "title": "Color sensors- Station 2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Query to get the RGB and Brightness values together with timestamps\r\nSELECT \r\n    m1.timestamp,\r\n    m1.measurement_value as r_value,\r\n    m2.measurement_value as g_value,\r\n    m3.measurement_value as b_value,\r\n    m4.measurement_value as brightness\r\nFROM \r\n    dinasore.measurement m1\r\nJOIN dinasore.measurement m2 ON m1.timestamp = m2.timestamp\r\nJOIN dinasore.measurement m3 ON m1.timestamp = m3.timestamp\r\nJOIN dinasore.measurement m4 ON m1.timestamp = m4.timestamp\r\nWHERE \r\n    m1.sensor_id=9 -- Color Sensor R\r\n    AND m2.sensor_id=10 -- Color Sensor G\r\n    AND m3.sensor_id=11 -- Color Sensor B\r\n    AND m4.sensor_id=12 -- Color Sensor Brightness\r\nORDER BY \r\n    m1.timestamp DESC"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 0, "w": 24, "x": 0, "y": 4 },
   "repeat": "rule_priority",
   "targets": [
    {
     "rawSql": "WITH rule_relations AS (\r\n  SELECT \r\n    r.rule_id,\r\n    r.rule_value,\r\n    r.rule_priority,\r\n    'sensor' as relation_type,\r\n    s.sensor_id as related_id,\r\n    s.tipo as related_name\r\n  FROM dinasore.rules r\r\n  JOIN dinasore.sensor s ON r.rule_id = s.rule_id\r\n  \r\n  UNION ALL\r\n  \r\n  SELECT \r\n    r.rule_id,\r\n    r.rule_value,\r\n    r.rule_priority,\r\n    'actuator' as relation_type,\r\n    a.actuator_id as related_id,\r\n    a.type as related_name\r\n  FROM dinasore.rules r\r\n  JOIN dinasore.actuator a ON r.rule_id = a.rule_id\r\n  \r\n  UNION ALL\r\n  \r\n  SELECT \r\n    r.rule_id,\r\n    r.rule_value,\r\n    r.rule_priority,\r\n    'cell' as relation_type,\r\n    c.cell_id as related_id,\r\n    c.tipo as related_name\r\n  FROM dinasore.rules r\r\n  JOIN dinasore.cell c ON r.rule_id = c.rule_id\r\n  \r\n  UNION ALL\r\n  \r\n  SELECT \r\n    r.rule_id,\r\n    r.rule_value,\r\n    r.rule_priority,\r\n    'production_line' as relation_type,\r\n    p.production_line_id as related_id,\r\n    p.tipo as related_name\r\n  FROM dinasore.rules r\r\n  JOIN dinasore.production_line p ON r.rule_id = p.rule_id\r\n)\r\nSELECT * FROM rule_relations\r\nORDER BY rule_id, relation_type, related_id;"
    }
   ]
  },
  {
   "title": "Color Sensor- Station 5",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Query to get the RGB and Brightness values together with timestamps\r\nSELECT \r\n    m1.timestamp,\r\n    m1.measurement_value as r_value,\r\n    m2.measurement_value as g_value,\r\n    m3.measurement_value as b_value,\r\n    m4.measurement_value as brightness\r\nFROM \r\n    dinasore.measurement m1\r\nJOIN dinasore.measurement m2 ON m1.timestamp = m2.timestamp\r\nJOIN dinasore.measurement m3 ON m1.timestamp = m3.timestamp\r\nJOIN dinasore.measurement m4 ON m1.timestamp = m4.timestamp\r\nWHERE \r\n    m1.sensor_id=28 -- Color Sensor R\r\n    AND m2.sensor_id=29 -- Color Sensor G\r\n    AND m3.sensor_id=30 -- Color Sensor B\r\n    AND m4.sensor_id=31 -- Color Sensor Brightness\r\nORDER BY \r\n    m1.timestamp DESC"
    }
   ]
  },
  {
   "title": "Temperature Levels",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    \"timestamp\",\r\n    (CASE WHEN s.station_id = 1 THEN m.measurement_value END) AS \"Station 1\",\r\n    (CASE WHEN s.station_id = 2 THEN m.measurement_value END) AS \"Station 2\",\r\n    (CASE WHEN s.station_id = 3 THEN m.measurement_value END) AS \"Station 3\", \r\n    (CASE WHEN s.station_id = 4 THEN m.measurement_value END) AS \"Station 4\",\r\n    (CASE WHEN s.station_id = 5 THEN m.measurement_value END) AS \"Station 5\"\r\nFROM \r\n    dinasore.measurement m\r\nJOIN \r\n    dinasore.sensor s ON m.sensor_id = s.sensor_id\r\nWHERE \r\n    s.tipo = 'Temperature Sensor'\r\n    AND m.timestamp >= $__timeFrom()\r\n    AND m.timestamp <= $__timeTo()\r\nGROUP BY \r\n    m.timestamp,s.station_id,m.measurement_value\r\nORDER BY \r\n  m.timestamp;"
    }
   ]
  },
  {
   "title": "Lightning Levels",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    m.timestamp,\r\n    (CASE WHEN s.station_id = 1 THEN m.measurement_value END) AS \"Station 1\",\r\n    (CASE WHEN s.station_id = 2 THEN m.measurement_value END) AS \"Station 2\",\r\n    (CASE WHEN s.station_id = 3 THEN m.measurement_value END) AS \"Station 3\", \r\n    (CASE WHEN s.station_id = 4 THEN m.measurement_value END) AS \"Station 4\",\r\n    (CASE WHEN s.station_id = 5 THEN m.measurement_value END) AS \"Station 5\"\r\nFROM \r\n    dinasore.measurement m\r\nJOIN \r\n    dinasore.sensor s ON m.sensor_id = s.sensor_id\r\nWHERE \r\n    s.tipo = 'Light Sensor (Lux)'\r\n    AND m.timestamp >= $__timeFrom()\r\n    AND m.timestamp <= $__timeTo()\r\nGROUP BY \r\n    m.timestamp,s.station_id,m.measurement_value\r\nORDER BY \r\n  m.timestamp;"
    }
   ]
  },
  {
   "title": "Power",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    (CASE WHEN s.station_id = 1 THEN m.measurement_value END) AS \"Station 1 - Distributing Power (kW)\",\r\n    (CASE WHEN s.station_id = 2 THEN m.measurement_value END) AS \"Station 2 - Testing Power (kW)\",\r\n    (CASE WHEN s.station_id = 3 THEN m.measurement_value END) AS \"Station 3 - Processing Power (kW)\", \r\n    (CASE WHEN s.station_id = 4 THEN m.measurement_value END) AS \"Station 4 - Transporting Power (kW)\",\r\n    (CASE WHEN s.station_id = 5 THEN m.measurement_value END) AS \"Station 5 - Sorting Power (kW)\"\r\nFROM \r\n    dinasore.measurement m\r\nJOIN \r\n    dinasore.sensor s ON m.sensor_id = s.sensor_id\r\nWHERE \r\n    s.tipo = 'Power Consumption Sensor'\r\n    AND m.timestamp >= $__timeFrom()\r\n    AND m.timestamp <= $__timeTo()\r\nGROUP BY \r\n    m.timestamp,s,station_id,m.measurement_value\r\nORDER BY \r\n  m.timestamp;"
    }
   ]
  }
 ]
}