{
 "title": "Station Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "StationID",
    "query": "SELECT DISTINCT station_id \nFROM dinasore.sensor \nORDER BY station_id;"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"\n  width: 100%;\n  height: 100px;\n  background: linear-gradient(135deg, #27ae60, #2ecc71);\n  color: white;\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  padding: 0 30px;\n  font-size: 20px;\n  font-weight: bold;\n  border-radius: 8px;\n  box-sizing: border-box;\n\">\n  <div>🏭 Station Metrics Monitoring Dashboard</div>\n  <div>\n    <a href=\"/d/930122ff-4ef3-4351-ae53-f38ad5c228b0/home\" style=\"\n      color: white;\n      text-decoration: underline;\n      font-size: 14px;\n      font-weight: normal;\n      text-decoration: none;\n    \">\n      ⬅ Back to Home\n    </a>\n  </div>\n</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "options": {
    "content": "<h2 style=\"font-family: sans-serif; color: #fff; background: #222; padding: 10px 0px; border-radius: 6px;\">\n  📌 Considerations\n</h2>\n"
   }
  },
  {
   "type": "table",
   "description": "Notes on the machine functionality and purpose",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT note FROM dinasore.station WHERE station_id = $StationID "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "options": {
    "content": "<h2 style=\"font-family: sans-serif; color: #fff; background: #222; padding: 10px 0px; border-radius: 6px;\">\n  ⚡ Power Monitoring\n</h2>\n"
   }
  },
  {
   "title": "Power Consumption Station: ${StationID}",
   "type": "timeseries",
   "description": "Shows the power consumption chart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  m.timestamp AS \"time\",\r\n  m.measurement_value AS \"Power (kW)\"\r\nFROM \r\n  dinasore.measurement m\r\nJOIN \r\n  dinasore.sensor s ON m.sensor_id = s.sensor_id\r\nJOIN \r\n  dinasore.station st ON s.station_id = st.station_id\r\nWHERE \r\n  s.tipo = 'Power Consumption Sensor'\r\n  AND st.station_id = $StationID\r\n  AND m.timestamp BETWEEN $__timeFrom() AND $__timeTo()\r\nORDER BY \r\n  m.timestamp;\r\n"
    }
   ]
  },
  {
   "title": "Total State Time By Station ${StationID}",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  state,\r\n  SUM(duration_sec) AS total_duration_sec\r\nFROM\r\n  dinasore.state_with_duration\r\nWHERE\r\n  station_id = '$StationID'\r\nGROUP BY\r\n  state\r\nORDER BY\r\n  state;\r\n"
    }
   ]
  },
  {
   "title": "Time by Station ${StationID}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  state,\r\n  SUM(duration_sec) AS total_duration_sec\r\nFROM\r\n  dinasore.state_with_duration\r\nWHERE\r\n  station_id = '$StationID'\r\nGROUP BY\r\n  state\r\nORDER BY\r\n  state;\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 29 },
   "options": {
    "content": "<h2 style=\"font-family: sans-serif; color: #fff; background: #222; padding: 10px 0px; border-radius: 6px;\">\n  📡 Sensors & Actuators\n</h2>\n"
   }
  },
  {
   "title": "Sensors Station ${StationID}",
   "type": "table",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT *\r\nFROM dinasore.sensor \r\nWHERE station_id = $StationID "
    }
   ]
  },
  {
   "title": "Color Sensor Station ${StationID}",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  MAX(CASE WHEN s.sensor_id IN (9, 28) THEN m.measurement_value END) AS R,\r\n  MAX(CASE WHEN s.sensor_id IN (10, 29) THEN m.measurement_value END) AS G,\r\n  MAX(CASE WHEN s.sensor_id IN (11, 30) THEN m.measurement_value END) AS B\r\nFROM \r\n  dinasore.measurement m\r\nJOIN \r\n  dinasore.sensor s ON m.sensor_id = s.sensor_id\r\nWHERE \r\n  s.station_id = $StationID\r\n  AND s.sensor_id IN (9, 10, 11, 28, 29, 30)\r\n  AND m.timestamp BETWEEN $__timeFrom() AND $__timeTo();\r\n\r\n"
    }
   ]
  },
  {
   "title": "Actuators Station ${StationID}",
   "type": "table",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT * \r\nFROM dinasore.actuator\r\nWHERE station_id = $StationID "
    }
   ]
  }
 ]
}